theme: jekyll-theme-minimal

title: SMO Wiki
description: A beautiful snapshot version of the Wiki brought to you by the Social Media Observatory at HBI
logourl: 'images/mainlogo.png'
logoalt: HBI-Logo
